# Day 3 — NumPy Fundamentals

Today I started learning NumPy and how it is used to work with numerical data.  
I practiced the difference between Python lists and NumPy arrays, then worked with arrays that have different numbers of dimensions.

## Importing NumPy

NumPy is usually imported using the short name `np`.  
I also checked the installed version to make sure the library is working correctly.

In [1]:
import numpy as np
print(np.__version__)

2.5.1


## Python Lists and NumPy Arrays

A Python list and a NumPy array may look similar, but mathematical operations behave differently.

Multiplying a Python list repeats its values. Multiplying a NumPy array applies the calculation to every value in the array.

In [2]:
numbers_list = [1, 2, 3, 4]
numbers_array = np.array([1, 2, 3, 4])
print(numbers_list * 2)
print(numbers_array * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


The Python list was repeated twice, while every value in the NumPy array was multiplied by two.  
This is one example of a vectorized operation.

## Creating NumPy Arrays

NumPy provides different ways to create arrays.

I can create an array from existing values, fill it with zeros or ones, generate a sequence of numbers, or create random values.

### Creating an Array from a Python List

`np.array()` converts existing Python values into a NumPy array.

NumPy normally chooses the data type based on the values in the list.

In [3]:
integer_array = np.array([5, 10, 15, 20])
decimal_array = np.array([1.5, 2.5, 3.5])
float_array = np.array([1, 2, 3], dtype=float)

print("Integer array:", integer_array)
print("Integer dtype:", integer_array.dtype)

print("\nDecimal array:", decimal_array)
print("Decimal dtype:", decimal_array.dtype)

print("\nConverted to float:", float_array)
print("Converted dtype:", float_array.dtype)

Integer array: [ 5 10 15 20]
Integer dtype: int64

Decimal array: [1.5 2.5 3.5]
Decimal dtype: float64

Converted to float: [1. 2. 3.]
Converted dtype: float64


### Creating Arrays Filled with Zeros

`np.zeros()` creates an array where every value starts as zero.

The shape is passed inside parentheses. By default, the values have a floating-point data type.

In [4]:
zero_vector = np.zeros(5)
zero_matrix = np.zeros((2, 3))
integer_zeros = np.zeros((2, 3), dtype=int)

print("1D zeros:")
print(zero_vector)

print("\n2D zeros:")
print(zero_matrix)

print("\nInteger zeros:")
print(integer_zeros)

1D zeros:
[0. 0. 0. 0. 0.]

2D zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Integer zeros:
[[0 0 0]
 [0 0 0]]


### Creating Arrays Filled with Ones

`np.ones()` works like `np.zeros()`, but every value starts as one.

It is useful when I need an array with a known starting value.

In [5]:
one_vector = np.ones(4)
one_matrix = np.ones((3, 2), dtype=int)

print("1D ones:")
print(one_vector)

print("\n2D ones:")
print(one_matrix)

print("\nShape:", one_matrix.shape)

1D ones:
[1. 1. 1. 1.]

2D ones:
[[1 1]
 [1 1]
 [1 1]]

Shape: (3, 2)


### Creating Sequences with `np.arange()`

`np.arange()` creates a sequence using a start value, an end value, and a step.

Its general form is:

`np.arange(start, end, step)`

The end value is not included.

In [6]:
first_sequence = np.arange(5)
second_sequence = np.arange(2, 10)
even_sequence = np.arange(0, 11, 2)
counting_down = np.arange(10, 0, -2)

print("From 0 to before 5:", first_sequence)
print("From 2 to before 10:", second_sequence)
print("Even values:", even_sequence)
print("Counting down:", counting_down)

From 0 to before 5: [0 1 2 3 4]
From 2 to before 10: [2 3 4 5 6 7 8 9]
Even values: [ 0  2  4  6  8 10]
Counting down: [10  8  6  4  2]


### Creating Evenly Spaced Values with `np.linspace()`

`np.linspace()` creates a chosen number of evenly spaced values between a start and an end.

Unlike `np.arange()`, the ending value is included by default.

In [7]:
five_values = np.linspace(0, 1, 5)
temperature_points = np.linspace(10, 20, 6)

print("Five values from 0 to 1:")
print(five_values)

print("\nSix values from 10 to 20:")
print(temperature_points)

Five values from 0 to 1:
[0.   0.25 0.5  0.75 1.  ]

Six values from 10 to 20:
[10. 12. 14. 16. 18. 20.]


### `np.arange()` vs `np.linspace()`

Both functions create number sequences, but they control the sequence differently.

- `np.arange()` uses the distance between values as a step.
- `np.linspace()` uses the total number of values that should be created.

In [8]:
using_arange = np.arange(0, 11, 2)
using_linspace = np.linspace(0, 10, 6)

print("Using arange:", using_arange)
print("Using linspace:", using_linspace)

Using arange: [ 0  2  4  6  8 10]
Using linspace: [ 0.  2.  4.  6.  8. 10.]


### Creating Random Values

`np.random.rand()` creates random decimal values from `0` up to, but not including, `1`.

A random seed can be set so the same values appear again when the notebook is rerun.

In [9]:
np.random.seed(42)

random_vector = np.random.rand(4)
random_matrix = np.random.rand(2, 3)

print("Random 1D array:")
print(random_vector)

print("\nRandom 2D array:")
print(random_matrix)

Random 1D array:
[0.37454012 0.95071431 0.73199394 0.59865848]

Random 2D array:
[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]]


Using a fixed seed makes the random output reproducible.

This is useful because another person can rerun the notebook and obtain the same random values.

### Changing an Array Shape with `reshape()`

`reshape()` changes how the same values are arranged without changing the values themselves.

The total number of elements must remain the same.

In [10]:
sequence = np.arange(1, 13)

matrix_3_by_4 = sequence.reshape(3, 4)
matrix_2_by_6 = sequence.reshape(2, 6)

print("Original sequence:")
print(sequence)

print("\nShape (3, 4):")
print(matrix_3_by_4)

print("\nShape (2, 6):")
print(matrix_2_by_6)

Original sequence:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Shape (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


I used several NumPy functions to create arrays in different ways.

- `np.array()` created an array from existing values.
- `np.zeros()` and `np.ones()` created arrays with fixed starting values.
- `np.arange()` created a sequence using a step.
- `np.linspace()` created a selected number of evenly spaced values.
- `np.random.rand()` created random decimal values.
- `reshape()` changed how the values were arranged.

## Array Dimensions

NumPy arrays can have different numbers of dimensions.

- A 0D array contains one value.
- A 1D array contains one row of values.
- A 2D array contains rows and columns.
- A 3D array contains multiple 2D arrays.

The `ndim` attribute shows the number of dimensions in an array.

In [11]:
scores = np.array([[75, 82, 90],[68, 88, 95]])
print("Array:")
print(scores)

print("Dimensions:", scores.ndim)
print("Shape:", scores.shape)
print("Size:", scores.size)
print("Data type:", scores.dtype)

Array:
[[75 82 90]
 [68 88 95]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64


## Array Attributes

NumPy arrays have attributes that describe their structure.

- `ndim` gives the number of dimensions.
- `shape` gives the size of each dimension.
- `size` gives the total number of elements.
- `dtype` gives the data type stored in the array.

NumPy arrays need a consistent shape.  
For example, all rows in a 2D array should usually contain the same number of values.

## Indexing NumPy Arrays

Indexing is used to access one value from an array.



For a 1D array, I use one index.  


In [12]:
temperatures = np.array([18, 21, 24, 20, 17])

print("First value:", temperatures[0])
print("Third value:", temperatures[2])
print("Last value:", temperatures[-1])

First value: 18
Third value: 24
Last value: 17





For a 2D array, I use the row and column indices.  


In [13]:
student_scores = np.array([
    [80, 85, 90],
    [70, 75, 88],
    [92, 89, 95]
])

print(student_scores[0, 0])
print(student_scores[1, 2])
print(student_scores[-1, -1])

80
88
95


For a 3D array, I use the layer, row, and column indices.

In [14]:
data = np.array([
    [
        ["A", "B"],
        ["C", "D"]
    ],
    [
        ["E", "F"],
        ["G", "H"]
    ]
])

print(data[0, 0, 0])
print(data[0, 1, 1])
print(data[1, 0, 1])

A
D
F


## Slicing NumPy Arrays

Indexing gives me one value from an array, while slicing gives me a group of values.

The general slicing form is:

`array[start:end:step]`

The end index is not included in the result.

In [15]:
numbers = np.array([10, 20, 30, 40, 50, 60])

print("Original array:", numbers)
print("From index 1 to 3:", numbers[1:4])
print("Every second value:", numbers[::2])
print("Reversed array:", numbers[::-1])

Original array: [10 20 30 40 50 60]
From index 1 to 3: [20 30 40]
Every second value: [10 30 50]
Reversed array: [60 50 40 30 20 10]


 I noticed that the end index is excluded from the slice.

Leaving the start and end positions empty selects values from the whole array. A negative step can also reverse the array.

### Slicing a 2D Array

For a 2D array, I can slice rows and columns.

The first position selects the rows, and the second position selects the columns:

`array[row_selection, column_selection]`

In [16]:
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Slicing Rows

When only one slice is used with a 2D array, NumPy applies it to the rows.

In [17]:
print("First row:")
print(matrix[0])

print("\nFirst two rows:")
print(matrix[0:2])

print("\nEvery second row:")
print(matrix[::2])

print("\nRows in reverse order:")
print(matrix[::-1])

First row:
[1 2 3 4]

First two rows:
[[1 2 3 4]
 [5 6 7 8]]

Every second row:
[[ 1  2  3  4]
 [ 9 10 11 12]]

Rows in reverse order:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### Slicing Columns

To select columns from a 2D array, I use a comma.

The colon before the comma means that all rows are selected.

In [18]:
print("First column:")
print(matrix[:, 0])

print("\nFirst three columns:")
print(matrix[:, 0:3])

print("\nEvery second column:")
print(matrix[:, ::2])

First column:
[ 1  5  9 13]

First three columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

Every second column:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


### Slicing Rows and Columns Together

I can use a row slice and a column slice at the same time to extract a smaller section from a matrix.

In [19]:
top_left = matrix[0:2, 0:2]
top_right = matrix[0:2, 2:4]
bottom_left = matrix[2:4, 0:2]
bottom_right = matrix[2:4, 2:4]
print(matrix)
print("")
print("Top-left section:")
print(top_left)

print("\nTop-right section:")
print(top_right)

print("\nBottom-left section:")
print(bottom_left)

print("\nBottom-right section:")
print(bottom_right)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Top-left section:
[[1 2]
 [5 6]]

Top-right section:
[[3 4]
 [7 8]]

Bottom-left section:
[[ 9 10]
 [13 14]]

Bottom-right section:
[[11 12]
 [15 16]]


 The row slice is written before the comma, and the column slice is written after the comma.

This makes it possible to extract a specific part of a 2D array.

### Slicing Practice

Using the same matrix:

1. Select the middle two rows.
2. Select the first and third columns.
3. Select the top-right 2 × 2 section.
4. Reverse the order of the columns.

In [20]:
print(matrix[1:3,:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(matrix[:,::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [22]:
print(matrix[0:2,2:])

[[3 4]
 [7 8]]


In [23]:
print(matrix[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


The practice helped me understand that rows are selected before the comma and columns are selected after it.

I also used the step value to skip columns and reverse their order.

## Arithmetic and Vectorized Operations

NumPy can apply mathematical operations to a complete array without using a loop.

These operations are called vectorized operations because NumPy processes all values in the array at once.

### Scalar Arithmetic

Scalar arithmetic means applying one number to every value in an array.

I can use the normal arithmetic operators such as addition, subtraction, multiplication, division, and powers.

In [24]:
values = np.array([2, 4, 6, 8])

print("Original array:", values)
print("Add 1:", values + 1)
print("Subtract 2:", values - 2)
print("Multiply by 3:", values * 3)
print("Divide by 2:", values / 2)
print("Power of 2:", values ** 2)

Original array: [2 4 6 8]
Add 1: [3 5 7 9]
Subtract 2: [0 2 4 6]
Multiply by 3: [ 6 12 18 24]
Divide by 2: [1. 2. 3. 4.]
Power of 2: [ 4 16 36 64]


### Vectorized Math Functions

NumPy also provides mathematical functions that work directly on arrays.

Some useful examples are square root, rounding, rounding down, and rounding up.

In [25]:
decimal_values = np.array([1.2, 2.7, 3.5, 4.9])
square_values = np.array([1, 4, 9, 16])

print("Square roots:", np.sqrt(square_values))
print("Rounded:", np.round(decimal_values))
print("Rounded down:", np.floor(decimal_values))
print("Rounded up:", np.ceil(decimal_values))

Square roots: [1. 2. 3. 4.]
Rounded: [1. 3. 4. 5.]
Rounded down: [1. 2. 3. 4.]
Rounded up: [2. 3. 4. 5.]


### Calculating Circle Areas

I used `np.pi` with an array of radius values to calculate multiple circle areas at once.

In [26]:
radii = np.array([1, 2, 3, 4])

circle_areas = np.pi * radii ** 2

print("Radius values:", radii)
print("Circle areas:", np.round(circle_areas, 2))

Radius values: [1 2 3 4]
Circle areas: [ 3.14 12.57 28.27 50.27]


### Elementwise Arithmetic

When two arrays have the same shape, NumPy performs the operation between values at matching positions.

In [27]:
first_array = np.array([10, 20, 30, 40])
second_array = np.array([1, 2, 3, 4])

print("Addition:", first_array + second_array)
print("Subtraction:", first_array - second_array)
print("Multiplication:", first_array * second_array)
print("Division:", first_array / second_array)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


### Comparison Operators

Comparison operators check every value in an array and return a Boolean array containing `True` or `False`.

The Boolean result can then be used to select or update values that match a condition.

In [28]:
scores = np.array([45, 60, 72, 58, 90])

print("Scores:", scores)
print("Passed or not:", scores >= 60)
print("Passing scores:", scores[scores >= 60])

Scores: [45 60 72 58 90]
Passed or not: [False  True  True False  True]
Passing scores: [60 72 90]


### Updating Values Using a Condition

A condition can also be used to change only the values that match it.

I used a copy of the original array so the original scores would stay unchanged.

In [29]:
updated_scores = scores.copy()

updated_scores[updated_scores < 60] = 0

print("Original scores:", scores)
print("Updated scores:", updated_scores)

Original scores: [45 60 72 58 90]
Updated scores: [ 0 60 72  0 90]


NumPy applied arithmetic and mathematical functions directly to complete arrays.

I also used comparison operators to create Boolean arrays, select matching values, and update values based on a condition.

## Broadcasting

Broadcasting allows NumPy to perform operations on arrays with different but compatible shapes.

NumPy does not add missing values. Instead, it behaves as if the values along a dimension of size `1` are repeated until the shapes match.

Two dimensions are compatible when:

- They have the same size.
- One of them has size `1`.

The dimensions are compared from right to left.

In [30]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

row_values = np.array([1, 2, 3])

result = matrix + row_values

print("Matrix:")
print(matrix)

print("\nRow values:")
print(row_values)

print("\nBroadcasting result:")
print(result)

Matrix:
[[10 20 30]
 [40 50 60]]

Row values:
[1 2 3]

Broadcasting result:
[[11 22 33]
 [41 52 63]]


The one-dimensional array was added to every row of the matrix.

NumPy treated the array with shape `(3,)` like a row with shape `(1, 3)`, then repeated it across the rows during the operation.

### Broadcasting a Row and a Column

A row array and a column array can be broadcast together.

The row values are repeated downward, while the column values are repeated across the columns.

In [31]:
row = np.array([[1, 2, 3]])
column = np.array([
    [1],
    [2],
    [3]
])

multiplication_table = column * row

print("Row shape:", row.shape)
print("Column shape:", column.shape)

print("\nMultiplication table:")
print(multiplication_table)

Row shape: (1, 3)
Column shape: (3, 1)

Multiplication table:
[[1 2 3]
 [2 4 6]
 [3 6 9]]


The row had shape `(1, 3)` and the column had shape `(3, 1)`.

Broadcasting produced a result with shape `(3, 3)`. Each row contains the row values multiplied by one value from the column.

## Aggregate Functions

Aggregate functions summarize multiple values into a smaller result.

They can summarize the whole array, or calculate separate results for each row or column using the `axis` parameter.

### Basic Aggregate Functions

The most common aggregate functions are:

- `sum()` for the total.
- `mean()` for the average.
- `min()` for the smallest value.
- `max()` for the largest value.
- `std()` for the standard deviation.
- `var()` for the variance.

In [32]:
numbers = np.array([10, 20, 30, 40, 50])

print("Values:", numbers)
print("Sum:", numbers.sum())
print("Mean:", numbers.mean())
print("Minimum:", numbers.min())
print("Maximum:", numbers.max())
print("Standard deviation:", numbers.std())
print("Variance:", numbers.var())

Values: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.142135623730951
Variance: 200.0


### Standard Deviation and Variance

Standard deviation measures how far the values are spread from their mean.

A small standard deviation means the values are close together. A larger standard deviation means they are more spread out.

Variance measures the same idea, but it is the square of the standard deviation.

In [33]:
close_values = np.array([19, 20, 20, 21, 20])
spread_values = np.array([5, 10, 20, 30, 35])

print("Close values mean:", close_values.mean())
print("Close values standard deviation:", close_values.std())

print()

print("Spread values mean:", spread_values.mean())
print("Spread values standard deviation:", spread_values.std())

Close values mean: 20.0
Close values standard deviation: 0.6324555320336759

Spread values mean: 20.0
Spread values standard deviation: 11.40175425099138


Both arrays have similar averages, but their values are distributed differently.

The second array has a larger standard deviation because its values are farther from the mean.

In [34]:
data = np.array([2, 4, 6, 8, 10])

standard_deviation = data.std()
variance = data.var()

print("Standard deviation:", standard_deviation)
print("Variance:", variance)
print("Standard deviation squared:", standard_deviation ** 2)

Standard deviation: 2.8284271247461903
Variance: 8.0
Standard deviation squared: 8.000000000000002


### Finding the Position of Minimum and Maximum Values

`min()` and `max()` return the values themselves.

`argmin()` and `argmax()` return the index positions of the smallest and largest values.

In [35]:
temperatures = np.array([24, 19, 27, 22, 30])

print("Temperatures:", temperatures)

print("Minimum value:", temperatures.min())
print("Index of minimum value:", temperatures.argmin())

print("Maximum value:", temperatures.max())
print("Index of maximum value:", temperatures.argmax())

Temperatures: [24 19 27 22 30]
Minimum value: 19
Index of minimum value: 1
Maximum value: 30
Index of maximum value: 4


### Aggregate Functions with 2D Arrays

Without an `axis`, NumPy summarizes all values in the array.

Using an axis allows the function to calculate a separate result for every column or every row.

In [36]:
student_scores = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [95, 88, 92]
])

print("Student scores:")
print(student_scores)

print("\nTotal of all scores:", student_scores.sum())
print("Mean of all scores:", student_scores.mean())
print("Lowest score:", student_scores.min())
print("Highest score:", student_scores.max())

Student scores:
[[80 70 90]
 [60 75 85]
 [95 88 92]]

Total of all scores: 735
Mean of all scores: 81.66666666666667
Lowest score: 60
Highest score: 95


### Aggregating by Columns with `axis=0`

Using `axis=0` reduces the rows and returns one result for each column.

In [37]:
column_sums = student_scores.sum(axis=0)
column_means = student_scores.mean(axis=0)
column_minimums = student_scores.min(axis=0)
column_maximums = student_scores.max(axis=0)

print("Column sums:", column_sums)
print("Column means:", column_means)
print("Column minimums:", column_minimums)
print("Column maximums:", column_maximums)

Column sums: [235 233 267]
Column means: [78.33333333 77.66666667 89.        ]
Column minimums: [60 70 85]
Column maximums: [95 88 92]


### Aggregating by Rows with `axis=1`

Using `axis=1` reduces the columns and returns one result for each row.

In [38]:
row_sums = student_scores.sum(axis=1)
row_means = student_scores.mean(axis=1)
row_minimums = student_scores.min(axis=1)
row_maximums = student_scores.max(axis=1)

print("Row sums:", row_sums)
print("Row means:", row_means)
print("Row minimums:", row_minimums)
print("Row maximums:", row_maximums)

Row sums: [240 220 275]
Row means: [80.         73.33333333 91.66666667]
Row minimums: [70 60 88]
Row maximums: [90 85 95]


### Understanding the Axis Parameter

For a 2D array:

- `axis=0` returns one result for each column.
- `axis=1` returns one result for each row.

The selected axis is the direction that NumPy reduces during the calculation.

In [39]:
print("Array shape:", student_scores.shape)
print("Mean with axis=0:", student_scores.mean(axis=0))
print("Result shape:", student_scores.mean(axis=0).shape)

print()

print("Mean with axis=1:", student_scores.mean(axis=1))
print("Result shape:", student_scores.mean(axis=1).shape)

Array shape: (3, 3)
Mean with axis=0: [78.33333333 77.66666667 89.        ]
Result shape: (3,)

Mean with axis=1: [80.         73.33333333 91.66666667]
Result shape: (3,)


In [40]:
sales = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Sales:")
print(sales)

print("\nMean of each column:", sales.mean(axis=0))
print("Mean of each row:", sales.mean(axis=1))

Sales:
[[10 20 30]
 [40 50 60]]

Mean of each column: [25. 35. 45.]
Mean of each row: [20. 50.]


Aggregate functions helped me summarize arrays using totals, averages, minimums, maximums, standard deviation, and variance.

I also learned that `argmin()` and `argmax()` return index positions instead of values.

For 2D arrays, `axis=0` produces one result for each column, while `axis=1` produces one result for each row.

## Boolean Filtering

Boolean filtering is used to select values that satisfy a condition.

A comparison creates a Boolean array containing `True` and `False`. I can then use this Boolean array as a mask to keep only the matching values.

In [41]:
ages = np.array([12, 17, 18, 25, 40, 65, 72])

under_18_mask = ages < 18
under_18 = ages[under_18_mask]

print("Ages:", ages)
print("Boolean mask:", under_18_mask)
print("Ages under 18:", under_18)

Ages: [12 17 18 25 40 65 72]
Boolean mask: [ True  True False False False False False]
Ages under 18: [12 17]


The condition created one Boolean value for every age.

Only the values whose condition was `True` appeared in the filtered array.


### Comparison Conditions

Filtering can use the normal comparison operators:

- `>` greater than
- `<` less than
- `>=` greater than or equal
- `<=` less than or equal
- `==` equal to
- `!=` not equal to

In [42]:
scores = np.array([45, 60, 72, 58, 90, 60])

print("Scores greater than 60:", scores[scores > 60])
print("Scores at least 60:", scores[scores >= 60])
print("Scores equal to 60:", scores[scores == 60])
print("Scores not equal to 60:", scores[scores != 60])

Scores greater than 60: [72 90]
Scores at least 60: [60 72 90 60]
Scores equal to 60: [60 60]
Scores not equal to 60: [45 72 58 90]


### Filtering a 2D Array

Boolean filtering can also be used with a 2D array.

The matching values are returned as a one-dimensional array, even when the original array has more than one dimension.

In [43]:
matrix = np.array([
    [12, 7, 20],
    [5, 18, 9]
])

greater_than_10 = matrix[matrix > 10]

print("Original matrix:")
print(matrix)

print("\nBoolean condition:")
print(matrix > 10)

print("\nValues greater than 10:")
print(greater_than_10)

print("\nOriginal shape:", matrix.shape)
print("Filtered shape:", greater_than_10.shape)

Original matrix:
[[12  7 20]
 [ 5 18  9]]

Boolean condition:
[[ True False  True]
 [False  True False]]

Values greater than 10:
[12 20 18]

Original shape: (2, 3)
Filtered shape: (3,)


### Filtering with Multiple Conditions

To combine two conditions, NumPy uses:

- `&` for AND
- `|` for OR

Each condition should be placed inside parentheses.

In [44]:
ages = np.array([12, 17, 18, 25, 40, 65, 72])

working_age = ages[(ages >= 18) & (ages < 65)]

print("All ages:", ages)
print("Ages from 18 to under 65:", working_age)

All ages: [12 17 18 25 40 65 72]
Ages from 18 to under 65: [18 25 40]


In [45]:
outside_working_age = ages[(ages < 18) | (ages >= 65)]

print("Under 18 or at least 65:", outside_working_age)

Under 18 or at least 65: [12 17 65 72]


### Filtering Even and Odd Values

The modulus operator `%` returns the remainder after division.

A value is even when its remainder after division by 2 is zero.

In [46]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_numbers = numbers[numbers % 2 == 0]
odd_numbers = numbers[numbers % 2 != 0]

print("All numbers:", numbers)
print("Even numbers:", even_numbers)
print("Odd numbers:", odd_numbers)

All numbers: [ 1  2  3  4  5  6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
Odd numbers: [1 3 5 7 9]


### Filtering Values Above the Mean

An aggregate function can be combined with Boolean filtering.

First, I calculated the mean. Then I selected the values that were greater than it.

In [47]:
values = np.array([10, 15, 20, 25, 30])

values_mean = values.mean()
above_mean = values[values > values_mean]

print("Values:", values)
print("Mean:", values_mean)
print("Values greater than the mean:", above_mean)

Values: [10 15 20 25 30]
Mean: 20.0
Values greater than the mean: [25 30]


### Selecting and Updating Values

Boolean filtering can create a new array of matching values.

It can also be used on the left side of an assignment to update the matching values in an existing array.

In [48]:
scores = np.array([45, 60, 72, 58, 90])

passing_scores = scores[scores >= 60]

updated_scores = scores.copy()
updated_scores[updated_scores < 60] = 0

print("Original scores:", scores)
print("Selected passing scores:", passing_scores)
print("Updated copy:", updated_scores)

Original scores: [45 60 72 58 90]
Selected passing scores: [60 72 90]
Updated copy: [ 0 60 72  0 90]


### Keeping the Original Shape with `np.where()`

Boolean indexing returns only matching values and may flatten the result.

`np.where()` checks each value and keeps the original shape by choosing one value when the condition is true and another value when it is false.

In [49]:
matrix = np.array([
    [12, 7, 20],
    [5, 18, 9]
])

filtered_matrix = np.where(matrix > 10, matrix, 0)

print("Original matrix:")
print(matrix)

print("\nValues greater than 10, with other values replaced by 0:")
print(filtered_matrix)

print("\nOriginal shape:", matrix.shape)
print("Result shape:", filtered_matrix.shape)

Original matrix:
[[12  7 20]
 [ 5 18  9]]

Values greater than 10, with other values replaced by 0:
[[12  0 20]
 [ 0 18  0]]

Original shape: (2, 3)
Result shape: (2, 3)


In [50]:
scores = np.array([45, 60, 72, 58, 90])

results = np.where(scores >= 60, "Pass", "Fail")

print("Scores:", scores)
print("Results:", results)

Scores: [45 60 72 58 90]
Results: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass']


### Boolean Indexing vs `np.where()`

Boolean indexing returns only the values that satisfy the condition.

`np.where()` keeps the original number and arrangement of elements, but replaces values depending on whether the condition is true or false.

Boolean filtering helped me select values using comparison conditions.

I used `&` and `|` to combine conditions, and the modulus operator to find even and odd values.

Boolean indexing returns only the matching values, while `np.where()` can preserve the original array shape and replace the values that do not match.

### Boolean Filtering Practice

Using the following array:

```python
practice_values = np.array([
    [5, 12, 18, 7],
    [20, 3, 15, 10],
    [8, 25, 14, 6]
])

Select all values greater than 10.

Select all values from 10 to 20, including both limits.

Select all even values.

Select values that are smaller than 8 or greater than 18.

Create a new array where values below 10 are replaced by -1, while keeping the original shape.

Calculate the mean and select all values above it.

In [51]:
practice_values = np.array([
    [5, 12, 18, 7],
    [20, 3, 15, 10],
    [8, 25, 14, 6]
])
print(practice_values[practice_values>10])
print(practice_values[(practice_values>10) & (practice_values<20)])
print(practice_values[practice_values%2==0])
print(np.where(practice_values>10 , practice_values, -1))
#Calculate the mean and select all values above it. IN TWO WAYS:
mean=np.mean(practice_values)
print(mean)
print(practice_values[practice_values>mean])
print(np.where(practice_values>mean, practice_values, "under"))

[12 18 20 15 25 14]
[12 18 15 14]
[12 18 20 10  8 14  6]
[[-1 12 18 -1]
 [20 -1 15 -1]
 [-1 25 14 -1]]
11.916666666666666
[12 18 20 15 25 14]
[['under' '12' '18' 'under']
 ['20' 'under' '15' 'under']
 ['under' '25' '14' 'under']]


## Official Day 3 Exercise

In this exercise, I will combine array creation, slicing, Boolean masking, aggregate functions, and broadcasting.

In [52]:
array=np.arange(1,17)
array2d=array.reshape(4,4)
print(array2d)
print()
print()

print(array2d.shape)
print()
print(array2d.dtype)
print()

print(array2d[-1])
print()
print()

print(array2d[:,1])
print()
print()
mean=array2d.mean()
print(array2d[array2d>mean])
row_values = np.array([10, 20, 30, 40])
broadcasting=row_values+array2d
print()
print()
print(broadcasting)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


(4, 4)

int64

[13 14 15 16]


[ 2  6 10 14]


[ 9 10 11 12 13 14 15 16]


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]


### Verifying the Broadcasting Result

I manually calculated the first row and compared it with the first row produced by broadcasting.

In [53]:
manual_first_row = array2d[0] + row_values
broadcast_first_row = broadcasting[0]

print("Manual first row:", manual_first_row)
print("Broadcast first row:", broadcast_first_row)

print(
    "Do both results match?",
    np.array_equal(manual_first_row, broadcast_first_row)
)

Manual first row: [11 22 33 44]
Broadcast first row: [11 22 33 44]
Do both results match? True
